WIFI_DEBUG = '\x01'
WIFI_TEST = '\x02'

WIFI_RESIZE_REQ = '\x08'
WIFI_RESIZE_ACK = '\x09'

WIFI_ARDUCAM_REQ = '\x03'
WIFI_ARDUCAM_DATA = '\x04'
WIFI_ARDUCAM_END = '\x05'

WIFI_INDUCTION_REQ = '\x06'
WIFI_INDUCTION_DATA = '\x07'

WIFI_RESET_REQ = '\x0A'
WIFI_RESET_ACK = '\x0B'
